### ISSUE TITLE
Sjekke opp timeouts i nitro

### ISSUE THREAD

**Issue by rbjornstad** [nais/nitro#1]
Siste oppgradering av prod-fss fikk timeout på Wait-steget under provisioning. Vi må gå over timeouts og se at de gir mening.

nodePods har bare 2 minutter timeout, og dersom apiserver bruker over 2 min på å komme opp vil første node feile.

**Comment by Muni10** [comment]
Kommer ikke til å gjøre noe her, før dette evt skjer igjen. Ikke skjedd de siste månedene.
